name: reminder_app
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: ">=2.15.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  path: ^1.8.0
  path_provider: ^2.0.8
  sqflite: ^2.0.2
  intl: ^0.17.0
  get: ^4.6.1
  flutter_local_notifications: ^6.0.0
  timezone: ^0.7.0
  month_picker_dialog: ^0.4.0
  day_picker: ^2.1.0
  flutter_picker: ^2.0.2
  shared_preferences: ^2.0.11
  googleapis: any
  google_sign_in: any
  firebase_auth: ^3.3.5
  flutter_spinkit: ^5.1.0
  connectivity_wrapper: ^1.0.6
  splash_screen_view: ^3.0.0
  pull_to_refresh: ^2.0.0
splash_screen_view:
  color: "#ffffff"
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/
